### PR TITLE
Add gitpod support

### PR DESCRIPTION
**Pull request by 0Grit**

### CODE REVIEW

**Comment by 0Grit** [comment]
@mniestroj where can I find a guide on the standards imposed by our gitlint?

**Comment by 0Grit** [comment]
And can we link to said guidance in the details of the gh action that is run?

**Comment by 0Grit** [comment]
@mniestroj is gitlint asking for a body message for the squashed PR?

**Comment by 0Grit** [comment]
@alvarowolfx I think this is going to pass can we sneak it in before the ethernet PR since it has no effect on the DSDK code itself?

**Review by alvarowolfx — APPROVED** [review]
LGTM.

**Pull request merged**
